name: Fetch JSON from Apple

on:
  push:
    branches:
      - main  # Change this to your main branch name if different
  schedule:
    - cron: '*/10 * * * *'  # every 10minutes
  workflow_dispatch:

jobs:
  fetch-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch JSON from Apple
        run: |
          mkdir -p cache
          curl -k -o cache/data.json https://gdmf.apple.com/v2/pmv

      - name: Commit JSON to repo
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add cache/data.json
          git commit -m "Update JSON data"
          git push
